"""
chessboard-corner-detect_organize.py
==================================
Organizes chessboard-corner-detect/ into YOLOv8-ready structure
under organized_data/corner_detection/

Run this ONCE from your project root (Chess-OCR/) before training.

Usage:
    python corner_detection_data_organize.py
"""

import os
import shutil
from pathlib import Path


# ─────────────────────────────────────────────
# CONFIG — adjust if your paths differ
# ─────────────────────────────────────────────

# Root of your project 
PROJECT_ROOT = Path(__file__).parent.resolve() / ".."

# Source: original dataset (never modified)
SRC_IMAGES = PROJECT_ROOT / "raw_data" / "chessboard-corner-detect" / "images"
SRC_LABELS = PROJECT_ROOT / "raw_data" / "chessboard-corner-detect" / "labels"

# Destination: clean YOLOv8-ready dataset
DST_ROOT   = PROJECT_ROOT / "organized_data" / "corner_detection"

# Sessions reserved for validation (rest go to train)
VAL_SESSIONS = {"83", "91", "99"}

# Image extension
IMG_EXT = ".jpg"


# ─────────────────────────────────────────────
# STEP 1 — Validate source exists
# ─────────────────────────────────────────────

def validate_source():
    assert SRC_IMAGES.exists(), f"Source images not found: {SRC_IMAGES}"
    assert SRC_LABELS.exists(), f"Source labels not found: {SRC_LABELS}"

    sessions_img = set(p.name for p in SRC_IMAGES.iterdir() if p.is_dir())
    sessions_lbl = set(p.name for p in SRC_LABELS.iterdir() if p.is_dir())

    assert sessions_img == sessions_lbl, (
        f"Mismatch between image and label sessions!\n"
        f"  Only in images: {sessions_img - sessions_lbl}\n"
        f"  Only in labels: {sessions_lbl - sessions_img}"
    )

    print(f"[OK] Source validated")
    print(f"     {len(sessions_img)} sessions found: {sorted(sessions_img, key=int)}")
    print(f"     Val sessions : {sorted(VAL_SESSIONS, key=int)}")
    print(f"     Train sessions: {sorted(sessions_img - VAL_SESSIONS, key=int)}")
    return sessions_img


# ─────────────────────────────────────────────
# STEP 2 — Create destination folders
# ─────────────────────────────────────────────

def create_dirs():
    dirs = [
        DST_ROOT / "images" / "train",
        DST_ROOT / "images" / "val",
        DST_ROOT / "labels" / "train",
        DST_ROOT / "labels" / "val",
    ]
    for d in dirs:
        d.mkdir(parents=True, exist_ok=True)
    print(f"\n[OK] Destination folders created under: {DST_ROOT}")


# ─────────────────────────────────────────────
# STEP 3 — Copy & flatten files
# ─────────────────────────────────────────────

def copy_files(sessions):
    stats = {"train_img": 0, "val_img": 0, "missing_label": 0, "missing_image": 0}

    for session in sorted(sessions, key=int):
        split      = "val" if session in VAL_SESSIONS else "train"
        img_src    = SRC_IMAGES / session
        lbl_src    = SRC_LABELS / session
        img_dst    = DST_ROOT / "images" / split
        lbl_dst    = DST_ROOT / "labels" / split

        image_files = sorted(img_src.glob(f"*{IMG_EXT}"))

        if not image_files:
            print(f"  [WARN] No images found in session {session}, skipping.")
            continue

        for img_path in image_files:
            stem      = img_path.stem          # e.g. G000_IMG003
            lbl_path  = lbl_src / f"{stem}.txt"

            # Skip if label missing
            if not lbl_path.exists():
                print(f"  [WARN] Label missing for {img_path.name}, skipping.")
                stats["missing_label"] += 1
                continue

            # Copy image
            shutil.copy2(img_path, img_dst / img_path.name)

            # Copy label
            shutil.copy2(lbl_path, lbl_dst / lbl_path.name)

            stats[f"{split}_img"] += 1

    return stats


# ─────────────────────────────────────────────
# STEP 4 — Write data.yaml
# ─────────────────────────────────────────────

def write_yaml():
    # Use forward slashes — works on both Windows and Linux/Colab
    yaml_path = DST_ROOT / "data.yaml"

    yaml_content = """# YOLOv8 Pose — Chessboard Corner Detection
# Auto-generated by corner_detection_data_organize.py
# path is relative to Chess-OCR/ (project root)
# Make sure you run training from Chess-OCR/ directory

path: .   # Chess-OCR/ project root

train: organized_data/corner_detection/images/train
val:   organized_data/corner_detection/images/val

# Classes
nc: 1
names:
  - chessboard

# Keypoint config: 4 corners, each with (x, y, visibility)
kpt_shape: [4, 3]

# Keypoint order (consistent across all labels):
#   kpt 0 — Top-Left     corner
#   kpt 1 — Top-Right    corner
#   kpt 2 — Bottom-Left  corner
#   kpt 3 — Bottom-Right corner
"""

    yaml_path.write_text(yaml_content)
    print(f"\n[OK] data.yaml written to: {yaml_path}")


# ─────────────────────────────────────────────
# STEP 5 — Verify output
# ─────────────────────────────────────────────

def verify_output():
    splits = ["train", "val"]
    print("\n[OK] Final dataset summary:")
    print(f"     {'Split':<10} {'Images':>8} {'Labels':>8} {'Match':>8}")
    print(f"     {'-'*36}")

    all_ok = True
    for split in splits:
        imgs   = list((DST_ROOT / "images" / split).glob(f"*{IMG_EXT}"))
        lbls   = list((DST_ROOT / "labels" / split).glob("*.txt"))
        match  = len(imgs) == len(lbls)
        status = "YES" if match else "NO ← MISMATCH"
        print(f"     {split:<10} {len(imgs):>8} {len(lbls):>8} {status:>8}")
        if not match:
            all_ok = False

    if all_ok:
        print(f"\n  Dataset is clean and ready for training.")
    else:
        print(f"\n  [ERROR] Image/label count mismatch — check warnings above.")

    return all_ok


# ─────────────────────────────────────────────
# STEP 6 — Check for duplicate filenames
# ─────────────────────────────────────────────

def check_duplicates():
    """
    Since all sessions use G0XX_IMGYYY naming, filenames should be
    globally unique. This just double-checks.
    """
    for split in ["train", "val"]:
        names = [p.name for p in (DST_ROOT / "images" / split).glob(f"*{IMG_EXT}")]
        dupes = [n for n in names if names.count(n) > 1]
        if dupes:
            print(f"\n  [WARN] Duplicate filenames in {split}: {set(dupes)}")
        else:
            print(f"[OK] No duplicate filenames in {split}")


# ─────────────────────────────────────────────
# MAIN
# ─────────────────────────────────────────────

def main():
    print("=" * 55)
    print("  Corner Detection — Data Organization Script")
    print("=" * 55)

    # Check if destination already exists
    if DST_ROOT.exists():
        response = input(
            f"\n  [!] Destination already exists: {DST_ROOT}\n"
            f"      Overwrite? (y/n): "
        ).strip().lower()
        if response != "y":
            print("  Aborted.")
            return
        shutil.rmtree(DST_ROOT)
        print(f"  Cleared existing destination.")

    sessions = validate_source()
    create_dirs()

    print(f"\n  Copying and flattening files...")
    stats = copy_files(sessions)

    print(f"\n  Copied → train: {stats['train_img']} images")
    print(f"  Copied → val  : {stats['val_img']} images")

    if stats["missing_label"] > 0:
        print(f"  [WARN] Skipped {stats['missing_label']} images (missing labels)")

    write_yaml()
    verify_output()
    check_duplicates()

    print("\n" + "=" * 55)
    print("  Done! Your dataset is ready for YOLOv8 training.")
    print(f"  data.yaml → {DST_ROOT / 'data.yaml'}")
    print("=" * 55)


if __name__ == "__main__":
    main()
